# Network policy for the openshift-apiserver-operator pod.
#
# Egress:
# - Allow all egress to support communication with the Kubernetes API server,
#   whose IP address and port are not known at manifest time. This implicitly
#   covers DNS resolution as well.
#
# Ingress:
# - Allow ingress on port 8443 (metrics) so that Prometheus can scrape metrics
#   from the operator.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-operator
  namespace: openshift-apiserver-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  podSelector:
    matchLabels:
      app: openshift-apiserver-operator
  ingress:
  - ports:
    - protocol: TCP
      port: 8443
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
