---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:node-config-reader
  namespace: openshift-node
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
