---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:node-config-reader
  namespace: openshift-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:node-config-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:nodes
