---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:image-pruner
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - replicationcontrollers
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - limitranges
    verbs:
      - list
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - buildconfigs
      - builds
    verbs:
      - get
      - list
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - images
    verbs:
      - delete
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - images
      - imagestreams
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams/status
    verbs:
      - update
