---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: cluster-debugger
rules:
  - nonResourceURLs:
      - /debug/pprof
      - /debug/pprof/*
      - /metrics
    verbs:
      - get
