---
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        storage.openshift.io/aggregate-to-storage-admin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: storage-admin
rules: null
