---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: Grants the right to push and pull images from within a project.
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:image-pusher
rules:
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams/layers
    verbs:
      - get
      - update
