---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:openshift:discovery
rules:
  - nonResourceURLs:
      - /version
      - /version/*
      - /api
      - /api/*
      - /apis
      - /apis/*
      - /oapi
      - /oapi/*
      - /openapi/v2
      - /swaggerapi
      - /swaggerapi/*
      - /swagger.json
      - /swagger-2.0.0.pb-v1
      - /osapi
      - /osapi/
      - /.well-known
      - /.well-known/oauth-authorization-server
      - /
    verbs:
      - get
