---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:openshift:controller:resourcequota-controller
rules:
  - apiGroups:
      - ""
    resources:
      - resourcequotas/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - resourcequotas
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
