---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:sdn-manager
rules:
  - apiGroups:
      - ""
      - network.openshift.io
    resources:
      - hostsubnets
      - netnamespaces
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - network.openshift.io
    resources:
      - clusternetworks
    verbs:
      - create
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
