---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:build-strategy-docker
rules:
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - builds/docker
      - builds/optimizeddocker
    verbs:
      - create
