apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: sudoer
rules:
  - apiGroups:
      - ""
      - user.openshift.io
    resourceNames:
      - system:admin
    resources:
      - systemusers
      - users
    verbs:
      - impersonate
  - apiGroups:
      - ""
      - user.openshift.io
    resourceNames:
      - system:masters
    resources:
      - groups
      - systemgroups
    verbs:
      - impersonate
