---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: A user that can request projects.
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: self-provisioner
rules:
  - apiGroups:
      - ""
      - project.openshift.io
    resources:
      - projectrequests
    verbs:
      - create
