---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: Grants the right to deploy within a project.  Used primarily with service accounts for automated deployments.
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:deployer
rules:
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
    verbs:
      - delete
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers/scale
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - list
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreamtags
      - imagetags
    verbs:
      - create
      - update
