---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:openshift:templateservicebroker-client
rules:
  - nonResourceURLs:
      - /brokers/template.openshift.io/*
    verbs:
      - delete
      - get
      - put
      - update
