---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:scope-impersonation
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - userextras/scopes.authorization.openshift.io
    verbs:
      - impersonate
