---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:openshift:controller:horizontal-pod-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:controller:horizontal-pod-autoscaler
subjects:
  - kind: ServiceAccount
    name: horizontal-pod-autoscaler
    namespace: openshift-infra
