---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: system:openshift:aggregate-to-edit
rules:
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - buildconfigs
      - buildconfigs/webhooks
      - builds
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - builds/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - buildconfigs/instantiate
      - buildconfigs/instantiatebinary
      - builds/clone
    verbs:
      - create
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - builds/details
    verbs:
      - update
  - apiGroups:
      - build.openshift.io
    resources:
      - jenkins
    verbs:
      - edit
      - view
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs
      - deploymentconfigs/scale
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigrollbacks
      - deploymentconfigs/instantiate
      - deploymentconfigs/rollback
    verbs:
      - create
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs/log
      - deploymentconfigs/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreamimages
      - imagestreammappings
      - imagestreams
      - imagestreams/secrets
      - imagestreamtags
      - imagetags
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams/layers
    verbs:
      - get
      - update
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreamimports
    verbs:
      - create
  - apiGroups:
      - ""
      - project.openshift.io
    resources:
      - projects
    verbs:
      - get
  - apiGroups:
      - ""
      - quota.openshift.io
    resources:
      - appliedclusterresourcequotas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes/custom-host
    verbs:
      - create
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - template.openshift.io
    resources:
      - processedtemplates
      - templateconfigs
      - templateinstances
      - templates
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - buildlogs
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - resourcequotausages
    verbs:
      - get
      - list
      - watch
