---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: system:openshift:aggregate-to-view
rules:
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - buildconfigs
      - buildconfigs/webhooks
      - builds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - builds/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - build.openshift.io
    resources:
      - jenkins
    verbs:
      - view
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs
      - deploymentconfigs/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs/log
      - deploymentconfigs/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreamimages
      - imagestreammappings
      - imagestreams
      - imagestreamtags
      - imagetags
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - project.openshift.io
    resources:
      - projects
    verbs:
      - get
  - apiGroups:
      - ""
      - quota.openshift.io
    resources:
      - appliedclusterresourcequotas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - template.openshift.io
    resources:
      - processedtemplates
      - templateconfigs
      - templateinstances
      - templates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - buildlogs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - resourcequotausages
    verbs:
      - get
      - list
      - watch
