---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  name: system:openshift:aggregate-to-cluster-reader
rules:
  - apiGroups:
      - ""
    resources:
      - componentstatuses
      - nodes
      - nodes/status
      - persistentvolumeclaims/status
      - persistentvolumes
      - persistentvolumes/status
      - pods/binding
      - pods/eviction
      - podtemplates
      - securitycontextconstraints
      - services/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
      - daemonsets/status
      - deployments/status
      - replicasets/status
      - statefulsets/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
      - customresourcedefinitions/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
      - apiservices/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs/status
      - jobs/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - node.k8s.io
    resources:
      - runtimeclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets/status
      - podsecuritypolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csidrivers
      - csinodes
      - storageclasses
      - volumeattachments
      - volumeattachments/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/approval
      - certificatesigningrequests/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - authorization.openshift.io
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindingrestrictions
      - rolebindings
      - roles
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - builds/details
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - images
      - imagesignatures
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams/layers
    verbs:
      - get
  - apiGroups:
      - ""
      - oauth.openshift.io
    resources:
      - oauthclientauthorizations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - project.openshift.io
    resources:
      - projects
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
      - project.openshift.io
    resources:
      - projectrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - quota.openshift.io
    resources:
      - clusterresourcequotas
      - clusterresourcequotas/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - network.openshift.io
    resources:
      - clusternetworks
      - egressnetworkpolicies
      - hostsubnets
      - netnamespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - security.openshift.io
    resources:
      - rangeallocations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - template.openshift.io
    resources:
      - brokertemplateinstances
      - templateinstances/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - user.openshift.io
    resources:
      - groups
      - identities
      - useridentitymappings
      - users
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - authorization.openshift.io
    resources:
      - localresourceaccessreviews
      - localsubjectaccessreviews
      - resourceaccessreviews
      - selfsubjectrulesreviews
      - subjectaccessreviews
      - subjectrulesreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - localsubjectaccessreviews
      - selfsubjectaccessreviews
      - selfsubjectrulesreviews
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - ""
      - security.openshift.io
    resources:
      - podsecuritypolicyreviews
      - podsecuritypolicyselfsubjectreviews
      - podsecuritypolicysubjectreviews
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
      - nodes/spec
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes/stats
    verbs:
      - create
      - get
  - nonResourceURLs:
      - '*'
    verbs:
      - get
