apiVersion: openshiftcontrolplane.config.openshift.io/v1
kind: OpenShiftAPIServerConfig
storageConfig:
  urls:
  - https://etcd.openshift-etcd.svc:2379
apiServerArguments:
  audit-log-format:
  - json
  audit-log-maxsize:
  - "100"
  audit-log-maxage:
  - 3
  audit-log-path:
  - /var/log/openshift-apiserver/audit.log
  audit-policy-file:
  - /var/run/configmaps/audit/default.yaml
  shutdown-delay-duration:
  - 3s # give SDN some time to converge
servingInfo:
  bindNetwork: "tcp"
