apiVersion: openshiftcontrolplane.config.openshift.io/v1
kind: OpenShiftAPIServerConfig
aggregatorConfig:
  clientCA: /var/run/configmaps/aggregator-client-ca/ca-bundle.crt
  allowedNames:
  - kube-apiserver-proxy
  - system:kube-apiserver-proxy
  - system:openshift-aggregator
  usernameHeaders:
  - X-Remote-User
  groupHeaders:
  - X-Remote-Group
  extraHeaderPrefixes:
  - X-Remote-Extra-
auditConfig:
  auditFilePath: "/var/log/openshift-apiserver/audit.log"
  enabled: true
  logFormat: "json"
  maximumFileSizeMegabytes: 100
  maximumRetainedFiles: 10
  policyConfiguration:
    apiVersion: audit.k8s.io/v1beta1
    kind: Policy
    # Don't generate audit events for all requests in RequestReceived stage.
    omitStages:
      - "RequestReceived"
    rules:
      # Don't log requests for events
      - level: None
        resources:
          - group: ""
            resources: ["events"]
      # Don't log authenticated requests to certain non-resource URL paths.
      - level: None
        userGroups: ["system:authenticated", "system:unauthenticated"]
        nonResourceURLs:
          - "/api*" # Wildcard matching.
          - "/version"
          - "/healthz"
      # A catch-all rule to log all other requests at the Metadata level.
      - level: Metadata
        # Long-running requests like watches that fall under this rule will not
        # generate an audit event in RequestReceived.
        omitStages:
          - "RequestReceived"
apiServerArguments:
  minimal-shutdown-duration:
  - 35s # give SDN some time to converge: 30s for iptable lock contention, 5s for the second try.