// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAPIServerConfig) DeepCopyInto(out *OpenShiftAPIServerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAPIServerConfig.
func (in *OpenShiftAPIServerConfig) DeepCopy() *OpenShiftAPIServerConfig {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAPIServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftAPIServerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAPIServerOperatorConfig) DeepCopyInto(out *OpenShiftAPIServerOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAPIServerOperatorConfig.
func (in *OpenShiftAPIServerOperatorConfig) DeepCopy() *OpenShiftAPIServerOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAPIServerOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftAPIServerOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAPIServerOperatorConfigList) DeepCopyInto(out *OpenShiftAPIServerOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenShiftAPIServerOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAPIServerOperatorConfigList.
func (in *OpenShiftAPIServerOperatorConfigList) DeepCopy() *OpenShiftAPIServerOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAPIServerOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftAPIServerOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAPIServerOperatorConfigSpec) DeepCopyInto(out *OpenShiftAPIServerOperatorConfigSpec) {
	*out = *in
	out.OperatorSpec = in.OperatorSpec
	in.UserConfig.DeepCopyInto(&out.UserConfig)
	in.ObservedConfig.DeepCopyInto(&out.ObservedConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAPIServerOperatorConfigSpec.
func (in *OpenShiftAPIServerOperatorConfigSpec) DeepCopy() *OpenShiftAPIServerOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAPIServerOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAPIServerOperatorConfigStatus) DeepCopyInto(out *OpenShiftAPIServerOperatorConfigStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAPIServerOperatorConfigStatus.
func (in *OpenShiftAPIServerOperatorConfigStatus) DeepCopy() *OpenShiftAPIServerOperatorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAPIServerOperatorConfigStatus)
	in.DeepCopyInto(out)
	return out
}
