---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:openshift:controller:image-import-controller
rules:
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - images
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreamimports
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
