---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:openshift:controller:unidling-controller
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - replicationcontrollers/scale
      - services
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments/scale
      - replicasets/scale
    verbs:
      - get
      - update
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs/scale
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
