---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:openshift:controller:deploymentconfig-controller
rules:
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers/scale
    verbs:
      - get
      - update
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs/status
    verbs:
      - update
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
